version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "build step"
  artificats:
    files:
     - "**/*"
    discard-paths: no
    base-directory: dist   
 post_build:
   commands:
     - echo "post_build step"