version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "build step"
artifacts:
  files:
    - dist/**/*
    - img/*
    - dist/index.html
  discard-paths: no

